splash = false
preload = /home/dougnizando/Imagens/hyprBackground/zelda.jpg
wallpaper = DP-1,/home/dougnizando/Imagens/hyprBackground/zelda.jpg
wallpaper = HDMI-A-1,/home/dougnizando/Imagens/hyprBackground/zelda.jpg